### ISSUE TITLE
如何更改item的间距

### ISSUE THREAD

**Issue by Bretra** [G-Xi0N/AYNavigationBar#1]

**Comment by Bretra** [comment]
如何更改item的间距，如题。尝试了目前修改item间距的方法，在咱们这个库里面，修改不了，请问，如何进行修改item的间距

**Comment by Bretra** [comment]
另外，关于修改返回按钮这个，是否提供下api，可以进行自定义话，目前只支持一个图片作为返回按钮

**Comment by Pircate** [comment]
> 另外，关于修改返回按钮这个，是否提供下api，可以进行自定义话，目前只支持一个图片作为返回按钮

这个是全局的返回按钮，如果自定义可以通过vc里面的navigation.item.leftbarbuttonitem

**Comment by Pircate** [comment]
> 
> 
> 如何更改item的间距，如题。尝试了目前修改item间距的方法，在咱们这个库里面，修改不了，请问，如何进行修改item的间距

item 间距在iOS11以上有变化，看这个[教程](https://juejin.im/post/5bd80582e51d45174218bfb9)

**Comment by Pircate** [comment]
@VillageMud 还有你的issue是不是提错地方了，现在只维护EachNavigationBar了
